---
  - name: disable swapping temporarily
    command: swapoff -a

  - name: Disable swap permanentlly
    lineinfile:
      path: /etc/fstab
      regexp: '/dev/mapper/cl_centos8-swap none                    swap    defaults        0 0'
      line: '#/dev/mapper/cl_centos8-swap none                    swap    defaults        0 0'

  - name: Create file to load modules
    lineinfile:
      path: /etc/modules-load.d/k8s.conf
      state: present
      line: "{{ item }}"
      create: yes
    with_items:
      - overlay
      - br_netfilter

  - name: Load overlay module
    modprobe:
      name: overlay
      state: present

  - name: Load br_netfilter module
    modprobe:
      name: br_netfilter
      state: present
  
  - name: Load kernel parameters
    lineinfile:
      path: /etc/sysctl.d/k8s.conf
      state: present
      line: "{{ item }}"
      create: yes
    with_items:
      - net.bridge.bridge-nf-call-iptables = 1
      - net.bridge.bridge-nf-call-ip6tables = 1
      - net.ipv4.ip_forward = 1

  - name: Apply sysctl params without reboot
    command: sysctl --system