---
  - name: Get command to join
    shell: kubeadm token create --print-join-command
    register: OutPut
    when: inventory_hostname == MasterHostName
    run_once: true

  - name: Set join command
    set_fact:
      join_command: "{{ OutPut.stdout_lines[0] }}"
    when: inventory_hostname == MasterHostName
    run_once: true

  - debug:
      msg: "{{ join_command }}"
    when: inventory_hostname == MasterHostName

  - name: On worker/s nodes joining cluster 
    shell: "{{ join_command }}"
    args:
      chdir: /home/{{ IcmpUser }}
      creates: NodeJoined.log
    when: inventory_hostname != MasterHostName
    ignore_errors: true
