---
  - name: Update pip3
    shell: pip3 install -U pip    

  - name: Installing Required kubenetes pip module
    pip:
      name:
        - kubernetes
      state: present
      executable: pip3

  - name: Install Flannel networking addon on master node
    shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml --validate=false >> PodNetworkSetup.log
    args:
      chdir: $HOME
      creates: PodNetworkSetup.log
    become: false
    run_once: true
    when: 
      - ansible_hostname == MasterHostName
      - PodNetworkAddon == "flannel"

  - name: Install Weave Net networking addon on master node
    command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml --validate=false
    become: false
    run_once: true
    when: 
      - ansible_hostname == MasterHostName
      - PodNetworkAddon != "flannel"
